version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: com.google.apis:google-api-services-bigquery
    versions:
    - v2-rev20201030-1.31.0
    - v2-rev20210118-1.31.0
    - v2-rev20210204-1.31.0
    - v2-rev20210215-1.31.0
    - v2-rev20210219-1.31.0
    - v2-rev20210303-1.31.0
    - v2-rev20210313-1.31.0
    - v2-rev20210327-1.31.0
    - v2-rev20210404-1.31.0
  - dependency-name: com.google.apis:google-api-services-pubsub
    versions:
    - v1-rev20201201-1.31.0
    - v1-rev20210208-1.31.0
    - v1-rev20210225-1.31.0
  - dependency-name: joda-time:joda-time
    versions:
    - 2.10.9
